name: id-diff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - matplotlib=3.7.2
  - numpy=1.24.3
  - tqdm=4.66.4
  - pandas=1.3.3
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - jupyterlab=3.2.1
  - notebook=6.4.5
  - ipykernel=6.4.1
  - ipython=7.23.1
  - jupyter_client=7.1.2
  - cython=0.29.24
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8
  - tensorboard=2.17.0
  - pip
  - pip:
      - jupyter-client==7.1.2
