name: id-diff
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - matplotlib=3.3.2
  - numpy=1.21.6
  - torch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8
  - tqdm=4.64.0
  - pandas=1.3.3
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - jupyterlab=3.2.1
  - notebook=6.4.5
  - ipykernel=6.4.1
  - ipython=7.23.1
  - jupyter_client=7.1.2
  - tensorboard=2.10.1
  - cython=0.29.24
  - pip
  - pip:
      - jupyter-client==7.1.2
